export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";

export const PRODUCT_BY_ID = "PRODUCT_BY_ID";
export const PRODUCT_BY_ID_SUCCESS = "PRODUCT_BY_ID_SUCCESS";

export const REMOVE_FROM_PRODUCTS = "REMOVE_FROM_PRODUCTS";
export const REMOVE_FROM_PRODUCTS_SUCCESS = "REMOVE_FROM_PRODUCTS_SUCCESS";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"


export const ALL_MANUFACTURERS = "ALL_MANUFACTURERS";
export const ALL_MANUFACTURERS_SUCCESS = "ALL_MANUFACTURERS_SUCCESS";

export const REMOVE_FROM_MANUFACTURERS = "REMOVE_FROM_MANUFACTURERS";
export const REMOVE_FROM_MANUFACTURERS_SUCCESS = "REMOVE_FROM_MANUFACTURERS_SUCCESS";

export const MANUFACTURER_BY_ID = "MANUFACTURER_BY_ID";
export const MANUFACTURER_BY_ID_SUCCESS = "MANUFACTURER_BY_ID_SUCCESS";

export const UPDATE_MANUFACTURER = "UPDATE_MANUFACTURER";
export const UPDATE_MANUFACTURER_SUCCESS = "UPDATE_MANUFACTURER_SUCCESS";

export const ADD_MANUFACTURER = "ADD_MANUFACTURER";
export const ADD_MANUFACTURER_SUCCESS = "ADD_MANUFACTURER_SUCCESS";

export const SET_USER = "SET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const LOGOUT = "LOGOUT";